-- MySQL Script generated by MySQL Workbench
-- mié 15 oct 2025 09:31:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turno_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `turno_system` ;

-- -----------------------------------------------------
-- Table `turno_system`.`ObraSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`ObraSocial` (
  `IdObraSocial` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdObraSocial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Cliente` (
  `IdCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `ObraSocial_IdObraSocial` INT NOT NULL,
  PRIMARY KEY (`IdCliente`),
  INDEX `fk_Cliente_ObraSocial1_idx` (`ObraSocial_IdObraSocial` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_ObraSocial1`
    FOREIGN KEY (`ObraSocial_IdObraSocial`)
    REFERENCES `turno_system`.`ObraSocial` (`IdObraSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Especialidad` (
  `IdEspecialidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Estado` (
  `IdEstado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Historia_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Historia_Medico` (
  `fechaTurno` DATE NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `info` TEXT NOT NULL,
  PRIMARY KEY (`fechaTurno`, `Cliente_IdCliente`),
  INDEX `Cliente_IdCliente` (`Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `Historia_Medico_ibfk_1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `turno_system`.`Cliente` (`IdCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Hospital` (
  `IdHospital` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdHospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Medico` (
  `DNI` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Especialidad_IdEspecialidad` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Especialidad_IdEspecialidad` (`Especialidad_IdEspecialidad` ASC) VISIBLE,
  CONSTRAINT `Medico_ibfk_1`
    FOREIGN KEY (`Especialidad_IdEspecialidad`)
    REFERENCES `turno_system`.`Especialidad` (`IdEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Turno` (
  `IdTurno` INT NOT NULL,
  `fechaPedido` DATE NOT NULL,
  `fechaTurno` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `duracion` TIME NOT NULL,
  `Estado_IdEstado` INT NOT NULL,
  `Medico_DNI` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `Hospital_IdHospital` INT NOT NULL,
  `info` TEXT NOT NULL,
  PRIMARY KEY (`IdTurno`),
  INDEX `Estado_IdEstado` (`Estado_IdEstado` ASC) VISIBLE,
  INDEX `Medico_DNI` (`Medico_DNI` ASC) VISIBLE,
  INDEX `Cliente_IdCliente` (`Cliente_IdCliente` ASC) VISIBLE,
  INDEX `Hospital_IdHospital` (`Hospital_IdHospital` ASC) VISIBLE,
  CONSTRAINT `Turno_ibfk_1`
    FOREIGN KEY (`Estado_IdEstado`)
    REFERENCES `turno_system`.`Estado` (`IdEstado`),
  CONSTRAINT `Turno_ibfk_2`
    FOREIGN KEY (`Medico_DNI`)
    REFERENCES `turno_system`.`Medico` (`DNI`),
  CONSTRAINT `Turno_ibfk_3`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `turno_system`.`Cliente` (`IdCliente`),
  CONSTRAINT `Turno_ibfk_4`
    FOREIGN KEY (`Hospital_IdHospital`)
    REFERENCES `turno_system`.`Hospital` (`IdHospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_as_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`ObraSocial_has_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`ObraSocial_has_Medico` (
  `ObraSocial_IdObraSocial` INT NOT NULL,
  `Medico_DNI` INT NOT NULL,
  PRIMARY KEY (`ObraSocial_IdObraSocial`, `Medico_DNI`),
  INDEX `fk_ObraSocial_has_Medico_Medico1_idx` (`Medico_DNI` ASC) VISIBLE,
  INDEX `fk_ObraSocial_has_Medico_ObraSocial1_idx` (`ObraSocial_IdObraSocial` ASC) VISIBLE,
  CONSTRAINT `fk_ObraSocial_has_Medico_ObraSocial1`
    FOREIGN KEY (`ObraSocial_IdObraSocial`)
    REFERENCES `turno_system`.`ObraSocial` (`IdObraSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ObraSocial_has_Medico_Medico1`
    FOREIGN KEY (`Medico_DNI`)
    REFERENCES `turno_system`.`Medico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
