-- MySQL Script generated by MySQL Workbench
-- lun 20 oct 2025 09:21:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turno_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;


-- -----------------------------------------------------
-- Table `turno_system`.`obra_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`obra_social` (
  `id_obra_social` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_obra_social`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`cliente` (
  `obra_social_id_obra_social` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  INDEX `fk_Cliente_ObraSocial1_idx` (`obra_social_id_obra_social` ASC) VISIBLE,
  INDEX `fk_cliente_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_ObraSocial1`
    FOREIGN KEY (`obra_social_id_obra_social`)
    REFERENCES `turno_system`.`obra_social` (`id_obra_social`),
  CONSTRAINT `usuario_fk_2`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `turno_system`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`especialidad` (
  `id_especialidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`medico` (
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `especialidad_id_especialidad` INT NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  INDEX `Especialidad_IdEspecialidad` (`especialidad_id_especialidad` ASC) VISIBLE,
  INDEX `fk_medico_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `Medico_ibfk_1`
    FOREIGN KEY (`especialidad_id_especialidad`)
    REFERENCES `turno_system`.`especialidad` (`id_especialidad`),
  CONSTRAINT `usuario_fk_1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `turno_system`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`estado` (
  `id_estado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`hospital` (
  `id_hospital` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`turno` (
  `id_turno` INT NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `fecha_turno` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `duracion` TIME NOT NULL,
  `estado_id_estado` INT NOT NULL,
  `hospital_id_hospital` INT NOT NULL,
  `medico_usuario_id_usuario` INT NOT NULL,
  `cliente_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_turno`),
  INDEX `Estado_IdEstado` (`estado_id_estado` ASC) VISIBLE,
  INDEX `Hospital_IdHospital` (`hospital_id_hospital` ASC) VISIBLE,
  INDEX `fk_turno_medico1_idx` (`medico_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_turno_cliente1_idx` (`cliente_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_turno_cliente1`
    FOREIGN KEY (`cliente_usuario_id_usuario`)
    REFERENCES `turno_system`.`cliente` (`usuario_id_usuario`),
  CONSTRAINT `fk_turno_medico1`
    FOREIGN KEY (`medico_usuario_id_usuario`)
    REFERENCES `turno_system`.`medico` (`usuario_id_usuario`),
  CONSTRAINT `Turno_ibfk_1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `turno_system`.`estado` (`id_estado`),
  CONSTRAINT `Turno_ibfk_4`
    FOREIGN KEY (`hospital_id_hospital`)
    REFERENCES `turno_system`.`hospital` (`id_hospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`clinica` (
  `id_turno` INT NOT NULL,
  `info` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_turno`),
  CONSTRAINT `Clinica_ibfk_1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `turno_system`.`turno` (`id_turno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`tipo_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`tipo_estudio` (
  `id_tipo_estudio` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`estudio` (
  `id_turno` INT NOT NULL,
  `informe` TEXT NULL DEFAULT NULL,
  `tipo_estudio_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_turno`),
  INDEX `TipoEstudioId` (`tipo_estudio_id` ASC) VISIBLE,
  CONSTRAINT `Estudio_ibfk_1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `turno_system`.`turno` (`id_turno`),
  CONSTRAINT `Estudio_ibfk_2`
    FOREIGN KEY (`tipo_estudio_id`)
    REFERENCES `turno_system`.`tipo_estudio` (`id_tipo_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`historia_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`historia_medico` (
  `fecha_turno` DATE NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `info` TEXT NOT NULL,
  `cliente_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`fecha_turno`, `cliente_id_cliente`),
  INDEX `fk_historia_medico_cliente1_idx` (`cliente_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_historia_medico_cliente1`
    FOREIGN KEY (`cliente_usuario_id_usuario`)
    REFERENCES `turno_system`.`cliente` (`usuario_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`imagen` (
  `id_imagen` INT NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `estudio_id_turno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `Estudio_IdTurno` (`estudio_id_turno` ASC) VISIBLE,
  CONSTRAINT `imagen_ibfk_1`
    FOREIGN KEY (`estudio_id_turno`)
    REFERENCES `turno_system`.`estudio` (`id_turno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`medico_has_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`medico_has_hospital` (
  `medico_usuario_id_usuario` INT NOT NULL,
  `hospital_id_hospital` INT NOT NULL,
  PRIMARY KEY (`medico_usuario_id_usuario`, `hospital_id_hospital`),
  INDEX `fk_medico_has_hospital_hospital1_idx` (`hospital_id_hospital` ASC) VISIBLE,
  INDEX `fk_medico_has_hospital_medico1_idx` (`medico_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_medico_has_hospital_hospital1`
    FOREIGN KEY (`hospital_id_hospital`)
    REFERENCES `turno_system`.`hospital` (`id_hospital`),
  CONSTRAINT `fk_medico_has_hospital_medico1`
    FOREIGN KEY (`medico_usuario_id_usuario`)
    REFERENCES `turno_system`.`medico` (`usuario_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`medico_has_obra_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`medico_has_obra_social` (
  `medico_usuario_id_usuario` INT NOT NULL,
  `obra_social_id_obra_social` INT NOT NULL,
  PRIMARY KEY (`medico_usuario_id_usuario`, `obra_social_id_obra_social`),
  INDEX `fk_medico_has_obra_social_obra_social1_idx` (`obra_social_id_obra_social` ASC) VISIBLE,
  INDEX `fk_medico_has_obra_social_medico1_idx` (`medico_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_medico_has_obra_social_medico1`
    FOREIGN KEY (`medico_usuario_id_usuario`)
    REFERENCES `turno_system`.`medico` (`usuario_id_usuario`),
  CONSTRAINT `fk_medico_has_obra_social_obra_social1`
    FOREIGN KEY (`obra_social_id_obra_social`)
    REFERENCES `turno_system`.`obra_social` (`id_obra_social`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`notificacion` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  `cliente_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_notificacion_cliente1_idx` (`cliente_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion_cliente1`
    FOREIGN KEY (`cliente_usuario_id_usuario`)
    REFERENCES `turno_system`.`cliente` (`usuario_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`chat` (
  `id_chat` INT NOT NULL,
  `cliente_usuario_id_usuario` INT NOT NULL,
  `medico_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk_chat_cliente1_idx` (`cliente_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_chat_medico1_idx` (`medico_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_chat_cliente1`
    FOREIGN KEY (`cliente_usuario_id_usuario`)
    REFERENCES `turno_system`.`cliente` (`usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_medico1`
    FOREIGN KEY (`medico_usuario_id_usuario`)
    REFERENCES `turno_system`.`medico` (`usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turno_system`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`mensaje` (
  `id_mensaje` INT NOT NULL,
  `contenido` TEXT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `chat_id_chat` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensaje_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_mensaje_chat1_idx` (`chat_id_chat` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `turno_system`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_chat1`
    FOREIGN KEY (`chat_id_chat`)
    REFERENCES `turno_system`.`chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
