-- MySQL Script generated by MySQL Workbench
-- vie 17 oct 2025 16:11:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turno_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turno_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `apellido` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_Administrador_Usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `turno_system` ;

-- -----------------------------------------------------
-- Table `turno_system`.`Obra_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Obra_social` (
  `Id_obra_social` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_obra_social`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Cliente` (
  `ObraSocial_IdObraSocial` INT NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  INDEX `fk_Cliente_ObraSocial1_idx` (`ObraSocial_IdObraSocial` ASC) VISIBLE,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_Cliente_ObraSocial1`
    FOREIGN KEY (`ObraSocial_IdObraSocial`)
    REFERENCES `turno_system`.`Obra_social` (`Id_obra_social`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Estado` (
  `IdEstado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Hospital` (
  `Id_hospital` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_hospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Turno` (
  `IdTurno` INT NOT NULL,
  `fechaPedido` DATE NOT NULL,
  `fechaTurno` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `duracion` TIME NOT NULL,
  `Estado_IdEstado` INT NOT NULL,
  `Medico_DNI` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `Hospital_IdHospital` INT NOT NULL,
  PRIMARY KEY (`IdTurno`),
  INDEX `Estado_IdEstado` (`Estado_IdEstado` ASC) VISIBLE,
  INDEX `Hospital_IdHospital` (`Hospital_IdHospital` ASC) VISIBLE,
  CONSTRAINT `Turno_ibfk_1`
    FOREIGN KEY (`Estado_IdEstado`)
    REFERENCES `turno_system`.`Estado` (`IdEstado`),
  CONSTRAINT `Turno_ibfk_4`
    FOREIGN KEY (`Hospital_IdHospital`)
    REFERENCES `turno_system`.`Hospital` (`Id_hospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Clinica` (
  `IdTurno` INT NOT NULL,
  `info` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IdTurno`),
  CONSTRAINT `Clinica_ibfk_1`
    FOREIGN KEY (`IdTurno`)
    REFERENCES `turno_system`.`Turno` (`IdTurno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Especialidad` (
  `IdEspecialidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEspecialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Tipo_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Tipo_estudio` (
  `Id_tipo_estudio` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_tipo_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Estudio` (
  `IdTurno` INT NOT NULL,
  `informe` TEXT NULL DEFAULT NULL,
  `TipoEstudioId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdTurno`),
  INDEX `TipoEstudioId` (`TipoEstudioId` ASC) VISIBLE,
  CONSTRAINT `Estudio_ibfk_1`
    FOREIGN KEY (`IdTurno`)
    REFERENCES `turno_system`.`Turno` (`IdTurno`),
  CONSTRAINT `Estudio_ibfk_2`
    FOREIGN KEY (`TipoEstudioId`)
    REFERENCES `turno_system`.`Tipo_estudio` (`Id_tipo_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Historia_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Historia_Medico` (
  `fechaTurno` DATE NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `info` TEXT NOT NULL,
  PRIMARY KEY (`fechaTurno`, `Cliente_IdCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Medico` (
  `Especialidad_IdEspecialidad` INT NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  INDEX `Especialidad_IdEspecialidad` (`Especialidad_IdEspecialidad` ASC) VISIBLE,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `Medico_ibfk_1`
    FOREIGN KEY (`Especialidad_IdEspecialidad`)
    REFERENCES `turno_system`.`Especialidad` (`IdEspecialidad`),
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`Notificacion` (
  `IdNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Cliente_IdCliente` INT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IdNotificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`ObraSocial_has_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`ObraSocial_has_Medico` (
  `ObraSocial_IdObraSocial` INT NOT NULL,
  `Medico_DNI` INT NOT NULL,
  PRIMARY KEY (`ObraSocial_IdObraSocial`, `Medico_DNI`),
  INDEX `fk_ObraSocial_has_Medico_ObraSocial1_idx` (`ObraSocial_IdObraSocial` ASC) VISIBLE,
  CONSTRAINT `fk_ObraSocial_has_Medico_ObraSocial1`
    FOREIGN KEY (`ObraSocial_IdObraSocial`)
    REFERENCES `turno_system`.`Obra_social` (`Id_obra_social`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`imagen` (
  `id_imagen` INT NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `Estudio_id_turno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `Estudio_IdTurno` (`Estudio_id_turno` ASC) VISIBLE,
  CONSTRAINT `imagen_ibfk_1`
    FOREIGN KEY (`Estudio_id_turno`)
    REFERENCES `turno_system`.`Estudio` (`IdTurno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turno_system`.`medico_has_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_system`.`medico_has_hospital` (
  `Medico_DNI` INT NOT NULL,
  `Hospital_id_hospital` INT NOT NULL,
  PRIMARY KEY (`Medico_DNI`, `Hospital_id_hospital`),
  INDEX `Hospital_IdHospital` (`Hospital_id_hospital` ASC) VISIBLE,
  CONSTRAINT `medico_has_hospital_ibfk_2`
    FOREIGN KEY (`Hospital_id_hospital`)
    REFERENCES `turno_system`.`Hospital` (`Id_hospital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
